/*
 * SensorPush Public API
 *
 * This is a swagger definition for the SensorPush public REST API. Download the definition file [here](https://api.sensorpush.com/api/v1/support/swagger/swagger-v1.json).
 *
 * API version: v1.0.20200621
 * Contact: support@sensorpush.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TokenResponse Response object for an oAuth authorization code.
type TokenResponse struct {
	// JWT oAuth access token. Pass this token to the data services via the http header 'Authorization'. Example 'Authorization' : 'Bearer <access token>'
	AccessToken string `json:"access_token,omitempty"`
	// TTL of the token in seconds
	ExpiresIn float32 `json:"expires_in,omitempty"`
	// JWT oAuth refresh token. Pass this token to the token service to retrieve a new access token.
	RefreshToken string `json:"refresh_token,omitempty"`
	// Type of token returned
	TokenType string `json:"token_type,omitempty"`
}
