/*
 * SensorPush Public API
 *
 * This is a swagger definition for the SensorPush public REST API. Download the definition file [here](https://api.sensorpush.com/api/v1/support/swagger/swagger-v1.json).
 *
 * API version: v1.0.20200621
 * Contact: support@sensorpush.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// Gateway struct for Gateway
type Gateway struct {
	// Date last alert was sent
	LastAlert time.Time `json:"last_alert,omitempty"`
	// Date the gateway was last seen
	LastSeen time.Time `json:"last_seen,omitempty"`
	// Detailed message associated with the gateway status.
	Message string `json:"message,omitempty"`
	// Name associated with a gateway
	Name string `json:"name,omitempty"`
	// Gateway is paired with a bluetooth device
	Paired string `json:"paired,omitempty"`
	// Samples associated with SensorPush gateway
	Samples map[string]Sample `json:"samples,omitempty"`
	// Version of Sensorpush software
	Version string `json:"version,omitempty"`
}
