/*
 * SensorPush Public API
 *
 * This is a swagger definition for the SensorPush public REST API. Download the definition file [here](https://api.sensorpush.com/api/v1/support/swagger/swagger-v1.json).
 *
 * API version: v1.0.20200621
 * Contact: support@sensorpush.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sensorpush
// SensorsRequest Request object for sensors.
type SensorsRequest struct {
	// filters sensors by active = (true|false). Defaults to true
	Active bool `json:"active,omitempty"`
	// Returns the results as the specified format (csv|json). Defaults to json
	Format string `json:"format,omitempty"`
}
