/*
 * SensorPush Public API
 *
 * This is a swagger definition for the SensorPush public REST API. Download the definition file [here](https://api.sensorpush.com/api/v1/support/swagger/swagger-v1.json).
 *
 * API version: v1.0.20200621
 * Contact: support@sensorpush.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sensorpush
// SamplesRequest Request object for samples.
type SamplesRequest struct {
	// Filters sensors by active = (true|false). Defaults to true
	Active bool `json:"active,omitempty"`
	// Queries that return large results are truncated (see comments on Samples endpoint). Set this flag to true for large reports. The report request will be queued and processed within 24 hours. Upon completion, the primary account holder will recieve an email with a link for download.
	Bulk bool `json:"bulk,omitempty"`
	// Returns the results as the specified format (csv|json). Defaults to json
	Format string `json:"format,omitempty"`
	// Number of samples to return.
	Limit int32 `json:"limit,omitempty"`
	// Filters samples by sensor id. This will be the same id returned in the sensors api call. The parameter value must be a list of strings. Example: sensors: [\"123.56789\"].
	Sensors []string `json:"sensors,omitempty"`
	// Start time to find samples (example: 2019-04-07T00:00:00-0400). Leave blank or zero to get the most recent samples.
	StartTime string `json:"startTime,omitempty"`
	// Stop time to find samples (example: 2019-04-07T10:30:00-0400). Leave blank or zero to get the most recent samples.
	StopTime string `json:"stopTime,omitempty"`
}
