/*
 * SensorPush Public API
 *
 * This is a swagger definition for the SensorPush public REST API. Download the definition file [here](https://api.sensorpush.com/api/v1/support/swagger/swagger-v1.json).
 *
 * API version: v1.0.20200621
 * Contact: support@sensorpush.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sensorpush
// Status struct for Status
type Status struct {
	// Date time when this service was last updated.
	Deployed string `json:"deployed,omitempty"`
	// Greeting message.
	Message string `json:"message"`
	// Current date time on the server in milliseconds.
	Ms int32 `json:"ms,omitempty"`
	// Active stack hosting this service.
	Stack string `json:"stack,omitempty"`
	// Current status of the api service.
	Status string `json:"status,omitempty"`
	// Current date time on the server.
	Time string `json:"time,omitempty"`
	// Version of this service currently deployed
	Version string `json:"version,omitempty"`
}
