/*
 * SensorPush Public API
 *
 * This is a swagger definition for the SensorPush public REST API. Download the definition file [here](https://api.sensorpush.com/api/v1/support/swagger/swagger-v1.json).
 *
 * API version: v1.0.20200621
 * Contact: support@sensorpush.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sensorpush
import (
	"time"
)
// ReportListing struct for ReportListing
type ReportListing struct {
	// Date file was last modified
	LastModified time.Time `json:"last_modified,omitempty"`
	// Name of the file
	Name string `json:"name,omitempty"`
	// File size
	Size string `json:"size,omitempty"`
}
