/*
 * SensorPush Public API
 *
 * This is a swagger definition for the SensorPush public REST API. Download the definition file [here](https://api.sensorpush.com/api/v1/support/swagger/swagger-v1.json).
 *
 * API version: v1.0.20200621
 * Contact: support@sensorpush.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sensorpush
// TokenRequest Request object for an oAuth accesstoken code.
type TokenRequest struct {
	// Client Id assigned to 3rd party applications. Contact support@sensorpush.com to register you app.
	ClientId string `json:"client_id,omitempty"`
	// Password associated with the client_id
	ClientSecret string `json:"client_secret,omitempty"`
	// This can be an authorization, access, or refresh token. Depending on which grant_type you are using.
	Code string `json:"code,omitempty"`
	// Accepted values are password, refresh_token, and access_token
	GrantType string `json:"grant_type,omitempty"`
	// User's password
	Password string `json:"password,omitempty"`
	// Redirection url to the 3rd party application once the user has signed into the sensorpush logon. This value should be URL encoded.
	RedirectUri string `json:"redirect_uri,omitempty"`
	// Refresh token used to request new access tokens.
	RefreshToken string `json:"refresh_token,omitempty"`
	// Email of the user to sign in.
	Username string `json:"username,omitempty"`
}
